// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lsp.proto

package gauge.messages;

public final class Lsp {
  private Lsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tlsp.proto\022\016gauge.messages\032\016messages.pr" +
      "oto2\234\007\n\nlspService\022X\n\014GetStepNames\022 .gau" +
      "ge.messages.StepNamesRequest\032!.gauge.mes" +
      "sages.StepNamesResponse\"\003\210\002\001\022I\n\tCacheFil" +
      "e\022 .gauge.messages.CacheFileRequest\032\025.ga" +
      "uge.messages.Empty\"\003\210\002\001\022d\n\020GetStepPositi" +
      "ons\022$.gauge.messages.StepPositionsReques" +
      "t\032%.gauge.messages.StepPositionsResponse" +
      "\"\003\210\002\001\022d\n\026GetImplementationFiles\022\025.gauge." +
      "messages.Empty\032..gauge.messages.Implemen" +
      "tationFileListResponse\"\003\210\002\001\022]\n\rImplement" +
      "Stub\022-.gauge.messages.StubImplementation" +
      "CodeRequest\032\030.gauge.messages.FileDiff\"\003\210" +
      "\002\001\022^\n\014ValidateStep\022#.gauge.messages.Step" +
      "ValidateRequest\032$.gauge.messages.StepVal" +
      "idateResponse\"\003\210\002\001\022R\n\010Refactor\022\037.gauge.m" +
      "essages.RefactorRequest\032 .gauge.messages" +
      ".RefactorResponse\"\003\210\002\001\022U\n\013GetStepName\022\037." +
      "gauge.messages.StepNameRequest\032 .gauge.m" +
      "essages.StepNameResponse\"\003\210\002\001\022d\n\017GetGlob" +
      "Patterns\022\025.gauge.messages.Empty\0325.gauge." +
      "messages.ImplementationFileGlobPatternRe" +
      "sponse\"\003\210\002\001\022M\n\013KillProcess\022\".gauge.messa" +
      "ges.KillProcessRequest\032\025.gauge.messages." +
      "Empty\"\003\210\002\001B!\n\016gauge.messages\252\002\016Gauge.Mes" +
      "sagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gauge.messages.Messages.getDescriptor(),
        }, assigner);
    gauge.messages.Messages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
