// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package gauge.messages;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\016gauge.messages\032\016messag" +
      "es.proto2\265\020\n\006Runner\022Y\n\014ValidateStep\022#.ga" +
      "uge.messages.StepValidateRequest\032$.gauge" +
      ".messages.StepValidateResponse\022Z\n\030Initia" +
      "lizeSuiteDataStore\022\025.gauge.messages.Empt" +
      "y\032\'.gauge.messages.ExecutionStatusRespon" +
      "se\022c\n\016StartExecution\022(.gauge.messages.Ex" +
      "ecutionStartingRequest\032\'.gauge.messages." +
      "ExecutionStatusResponse\022Y\n\027InitializeSpe" +
      "cDataStore\022\025.gauge.messages.Empty\032\'.gaug" +
      "e.messages.ExecutionStatusResponse\022k\n\022St" +
      "artSpecExecution\022,.gauge.messages.SpecEx" +
      "ecutionStartingRequest\032\'.gauge.messages." +
      "ExecutionStatusResponse\022]\n\033InitializeSce" +
      "narioDataStore\022\025.gauge.messages.Empty\032\'." +
      "gauge.messages.ExecutionStatusResponse\022s" +
      "\n\026StartScenarioExecution\0220.gauge.message" +
      "s.ScenarioExecutionStartingRequest\032\'.gau" +
      "ge.messages.ExecutionStatusResponse\022k\n\022S" +
      "tartStepExecution\022,.gauge.messages.StepE" +
      "xecutionStartingRequest\032\'.gauge.messages" +
      ".ExecutionStatusResponse\022Z\n\013ExecuteStep\022" +
      "\".gauge.messages.ExecuteStepRequest\032\'.ga" +
      "uge.messages.ExecutionStatusResponse\022j\n\023" +
      "FinishStepExecution\022*.gauge.messages.Ste" +
      "pExecutionEndingRequest\032\'.gauge.messages" +
      ".ExecutionStatusResponse\022r\n\027FinishScenar" +
      "ioExecution\022..gauge.messages.ScenarioExe" +
      "cutionEndingRequest\032\'.gauge.messages.Exe" +
      "cutionStatusResponse\022j\n\023FinishSpecExecut" +
      "ion\022*.gauge.messages.SpecExecutionEnding" +
      "Request\032\'.gauge.messages.ExecutionStatus" +
      "Response\022b\n\017FinishExecution\022&.gauge.mess" +
      "ages.ExecutionEndingRequest\032\'.gauge.mess" +
      "ages.ExecutionStatusResponse\022D\n\tCacheFil" +
      "e\022 .gauge.messages.CacheFileRequest\032\025.ga" +
      "uge.messages.Empty\022P\n\013GetStepName\022\037.gaug" +
      "e.messages.StepNameRequest\032 .gauge.messa" +
      "ges.StepNameResponse\022_\n\017GetGlobPatterns\022" +
      "\025.gauge.messages.Empty\0325.gauge.messages." +
      "ImplementationFileGlobPatternResponse\022S\n" +
      "\014GetStepNames\022 .gauge.messages.StepNames" +
      "Request\032!.gauge.messages.StepNamesRespon" +
      "se\022_\n\020GetStepPositions\022$.gauge.messages." +
      "StepPositionsRequest\032%.gauge.messages.St" +
      "epPositionsResponse\022_\n\026GetImplementation" +
      "Files\022\025.gauge.messages.Empty\032..gauge.mes" +
      "sages.ImplementationFileListResponse\022X\n\r" +
      "ImplementStub\022-.gauge.messages.StubImple" +
      "mentationCodeRequest\032\030.gauge.messages.Fi" +
      "leDiff\022M\n\010Refactor\022\037.gauge.messages.Refa" +
      "ctorRequest\032 .gauge.messages.RefactorRes" +
      "ponse\022A\n\004Kill\022\".gauge.messages.KillProce" +
      "ssRequest\032\025.gauge.messages.Empty2\257\007\n\010Rep" +
      "orter\022Z\n\027NotifyExecutionStarting\022(.gauge" +
      ".messages.ExecutionStartingRequest\032\025.gau" +
      "ge.messages.Empty\022b\n\033NotifySpecExecution" +
      "Starting\022,.gauge.messages.SpecExecutionS" +
      "tartingRequest\032\025.gauge.messages.Empty\022j\n" +
      "\037NotifyScenarioExecutionStarting\0220.gauge" +
      ".messages.ScenarioExecutionStartingReque" +
      "st\032\025.gauge.messages.Empty\022b\n\033NotifyStepE" +
      "xecutionStarting\022,.gauge.messages.StepEx" +
      "ecutionStartingRequest\032\025.gauge.messages." +
      "Empty\022^\n\031NotifyStepExecutionEnding\022*.gau" +
      "ge.messages.StepExecutionEndingRequest\032\025" +
      ".gauge.messages.Empty\022f\n\035NotifyScenarioE" +
      "xecutionEnding\022..gauge.messages.Scenario" +
      "ExecutionEndingRequest\032\025.gauge.messages." +
      "Empty\022^\n\031NotifySpecExecutionEnding\022*.gau" +
      "ge.messages.SpecExecutionEndingRequest\032\025" +
      ".gauge.messages.Empty\022V\n\025NotifyExecution" +
      "Ending\022&.gauge.messages.ExecutionEndingR" +
      "equest\032\025.gauge.messages.Empty\022P\n\021NotifyS" +
      "uiteResult\022$.gauge.messages.SuiteExecuti" +
      "onResult\032\025.gauge.messages.Empty\022A\n\004Kill\022" +
      "\".gauge.messages.KillProcessRequest\032\025.ga" +
      "uge.messages.Empty2\223\001\n\nDocumenter\022B\n\014Gen" +
      "erateDocs\022\033.gauge.messages.SpecDetails\032\025" +
      ".gauge.messages.Empty\022A\n\004Kill\022\".gauge.me" +
      "ssages.KillProcessRequest\032\025.gauge.messag" +
      "es.EmptyB!\n\016gauge.messages\252\002\016Gauge.Messa" +
      "gesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gauge.messages.Messages.getDescriptor(),
        }, assigner);
    gauge.messages.Messages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
